### ISSUE TITLE
aaslabels not found

### ISSUE THREAD

**Issue by niallomahony93** [ukdsvl/GUML#1]
Your code references several dataset  .mat files ( '../data_DML/data_DML_FashMNIST_tSNE.mat' and aas_labels_fgvc/aas_labels_full_CUB_googlenet.mat) that are not included in your repository. Where can I find these? If the dataset is not available, would mind giving an example of the format of the labels so I can recreate it for my own data, please?

**Comment by ukdsvl** [comment]
1. '../data_DML/data_DML_FashMNIST_tSNE.mat' : 
It should contain :
dict_keys(['__header__', '__version__', '__globals__', 'data_tr', 'data_tst', 'data_val', 'difPairInds', 'npair_constraints', 'points', 'simPairInds', 'triplets', 'truelabels_tr', 'truelabels_tst', 'truelabels_val'])

where, the entities are essentially np arrays. 
eg, data_tr is a dxN train data matrix (i^th column representing the i^th sample), 
truelabels_tr is a Nx1 matrix with the corresponding ground truth labels, 
and so on.. feel free to keep only the variables useful for you. Just make sure which ones u want to use in your code later and prepare your data in similar lines.
'triplets': Tx3 matrix, with T being the number of triplets with each row having the index of anchor , positive and negative (index wrt the data matrix).
'simPairInds': indices of pairs of examples that are sematically similar, ('difPairInds' for the dissimilar ones) // perhaps u wont be needing these variables.. so do not create them
'npair_constraints': Pxt matrix of indices of examples. P: number of tuples, where each row would represent a tuple such that the tuple has the first two indices pointing to examples sematically similar to each other (first being the anchor and the second being positive), the rest of the indices just point to multiple negative examples.


2. 'aas_labels_fgvc/aas_labels_full_CUB_googlenet.mat' : just keep a Nx1 matrix containing the pseudo-labels (depends on how you obtain).

I hope this gives you some idea. Apologies for not being able to maintain a bit cleaner repo.
